development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_development
  pool: 5
  timeout: 5000
  username: zeal
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  pool: 5
  timeout: 5000
  username: zeal
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: portfolio_production
  pool: 5
  timeout: 5000
  username: zeal
  password: